### ISSUE TITLE
Search by UPC

### ISSUE THREAD

**Issue by najpodge** [yarian/brewerydb#2]
Hi, I was wondering if there is the capability to do a beer search by UPC, as shown here: http://www.brewerydb.com/developers/docs-endpoint/search_upc

Thanks!

**Comment by yarian** [comment]
Hey, currently there is not but I could look into it soon. Or if you wanted to give it a whirl and submit a pull request that'd work too.

**Comment by yarian** [comment]
Added the capability via a search_upc method. It works like all the other endpoint methods. What you get is:

search_upc(options={})

So an example query would be:

search_upc({'code':'blahblahblah'})
